[PARSER]
    Name        log_path
    Format      regex
    Regex       ^/logs/(?<service_name>[^/]+)\.log$

[PARSER]
    Name        python_app
    Format      regex
    Regex       ^(?<app_time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) - (?<level>[A-Z]+) - \[trace_id: (?<trace_id>[0-9a-fA-F]*), span_id: (?<span_id>[0-9a-fA-F]*)\] - (?<module>[^ ]+) - (?<message>.*)$
    Time_Key    app_time
    Time_Format %Y-%m-%d %H:%M:%S,%L

[PARSER]
    Name        reservation_id
    Format      regex
    Regex       (?i).*(?<reservation_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}).*
